version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: "Prepare"
          command: scripts/prepare_build_environment.sh

      - run:
          name: "Build"
          command: scripts/compile_kernel.sh

      - store_artifacts:
          path: /var/kernel_build/results

      - deploy:
          name: Deploy
          command: scripts/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
